version: 0.2

phases:
  install:
    commands:
      - sudo python3 -m venv venv
      - sudo source venv/bin/activate
      - sudo pip install -r requirements.txt
  build:
    commands:
      - echo Build started on `date`
      - touch /usr/var/jenkins/config.env
      - printf "SECRET_KEY=%s\n" "python3 -c "import secrets; print(secrets.token_hex(16))"" >> /usr/var/jenkins/config.env
      - echo "ADMIN_EMAIL=zacjaredawsdev@gmail.com" >> /usr/var/jenkins/config.env
      - echo "ADMIN_PASSWORD=password" >> /usr/var/jenkins/config.env
      - echo "REDISTOGO_URL=http://localhost:6379" >> /usr/var/jenkins/config.env
      - echo "FLASK_CONFIG=default" >> /usr/var/jenkins/config.env
      - gem install sass
      - sudo apt-get install redis-server
      - sudo apt-get install libpq-dev
      - python manage.py recreate_db
      - python manage.py setup_dev
      - python manage.py add_fake_data
      - source env/bin/activate
      - honcho start -e /usr/var/jenkins/config.env -f Local
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - web.py
    - appspec.yml
    - templates/layout.html
    - templates/test.html
    - scripts/mkdir.sh
    - scripts/start_flask.sh
    - scripts/stop_flask1.sh
    - scripts/stop_flask.py
