version: 0.2

phases:
  install:
    commands:
      - npm install
      - sudo yum update
      - sudo yum install ruby
      - sudo yum install wget
      - echo "#!/bin/bash CODEDEPLOY_BIN="/opt/codedeploy-agent/bin/codedeploy-agent" $CODEDEPLOY_BIN stop yum erase codedeploy-agent -y"
  build:
    commands:
      - npm test
      - cd /home/ec2-user
      - wget https://aws-codedeploy-us-east-1.s3.us-east-1.amazonaws.com/latest/install
      - chmod +x ./install
      - sudo ./install auto
      - sudo service codedeploy-agent status
artifacts:
  files:
    - '**/*'
